version: "3.7"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: scoutdb
      TZ: Europe/Bucharest
      PGTZ: Europe/Bucharest
    ports:
      - "54321:5432"
    volumes:
      - scout_pgdb:/var/lib/postgresql/scout_data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  scout_pgdb:
